[package]
name = "memory-flame-chart"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
memory-stats = "1.0"
relay-dynamic-config = { path = "../../relay-dynamic-config" }
serde_json = "1.0.116"

[lints]
workspace = true
