[package]
name = "project-config-memory"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
memory-stats = "1.0"
relay-dynamic-config = { path = "../../relay-dynamic-config" }
serde = "1.0.198"
serde_json = "1.0.116"
stats_alloc = "0.1.10"

[lints]
workspace = true
