[package]
name = "relay-test"
authors = ["Sentry <oss@sentry.io>"]
description = "Test utilities for Relay"
homepage = "https://getsentry.github.io/relay/"
repository = "https://github.com/getsentry/relay"
version = "24.2.0"
edition = "2021"
license-file = "../LICENSE.md"
publish = false

[dependencies]
axum = "0.6.20"
chrono = "0.4"
flate2 = "1.0.19"
hyper = "0.14"
relay-auth = { path = "../relay-auth" }
relay-base-schema = { path = "../relay-base-schema" }
relay-config = { path = "../relay-config" }
relay-dynamic-config = { path = "../relay-dynamic-config" }
relay-event-schema = { path = "../relay-event-schema" }
relay-log = { path = "../relay-log", features = ["test"] }
relay-quotas = { path = "../relay-quotas" }
relay-sampling = { path = "../relay-sampling" }
relay-system = { path = "../relay-system" }
reqwest = { version = "0.11", features = ["blocking"] }
serde = { workspace = true }
serde_json = { workspace = true }
tempfile = "3.8.0"
tokio = { workspace = true, features = ["full"] }
uuid = { workspace = true }
