[package]
name = "relay-test"
authors = ["Sentry <oss@sentry.io>"]
description = "Test utilities for Relay"
homepage = "https://getsentry.github.io/relay/"
repository = "https://github.com/getsentry/relay"
version = "24.2.0"
edition = "2021"
license-file = "../LICENSE.md"
publish = false

[dependencies]
relay-log = { path = "../relay-log", features = ["test"] }
relay-system = { path = "../relay-system" }
tokio = { workspace = true, features = ["full"]}
serde = { workspace = true }
serde_json = { workspace = true }
relay-base-schema = { path = "../relay-base-schema" }
uuid = { workspace = true }
reqwest = { version = "0.11", features = ["blocking"] }
tempfile = "3.8.0"
serde_yaml = { workspace = true }
relay-event-schema = { path = "../relay-event-schema" }
relay-sampling = { path = "../relay-sampling" }
relay-quotas = { path = "../relay-quotas" }
chrono = "0.4"
hyper = "0.14"
lazy_static = "1.4"
relay-dynamic-config = { path = "../relay-dynamic-config" }
relay-config = { path = "../relay-config" }
relay-auth = { path = "../relay-auth" }
flate2 = "1.0.19"
axum = { version = "0.6.20", features = [
    "headers",
    "macros",
    "matched-path",
    "multipart",
    "tracing",
] }
axum-server = "0.4.7"



